# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'obrazek.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-20, 0, 461, 301))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Dva = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Dva.setObjectName("Dva")
        self.horizontalLayout.addWidget(self.Dva)
        self.Jeden = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Jeden.setObjectName("Jeden")
        self.horizontalLayout.addWidget(self.Jeden)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.photo = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("../OneDrive/Pictures/278064809_507175804241163_6954978704654465515_n.png"))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")
        self.verticalLayout.addWidget(self.photo)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.Jeden.clicked.connect(self.show_one)
        self.Dva.clicked.connect(self.show_two)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Dva.setText(_translate("MainWindow", "Dva"))
        self.Jeden.setText(_translate("MainWindow", "Jeden"))

    def show_one(self):
        self.photo.setPixmap(QtGui.QPixmap("imgs/WIN_20220113_12_09_20_Pro.jpg"))

    def show_two(self):
        self.photo.setPixmap(QtGui.QPixmap("imgs/278064809_507175804241163_6954978704654465515_n.png"))
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
